### ISSUE TITLE
runtime exception : ProcessSupervisor

### ISSUE THREAD

**Issue by akrick** [jae-jae/QueryList-Puppeteer#5]
expose exceptions as below：

`#0 D:\wwwroot\pscraper\vendor\nesk\rialto\src\ProcessSupervisor.php(423): Nesk\Rialto\ProcessSupervisor->checkProcessStatus()
#1 D:\wwwroot\pscraper\vendor\nesk\rialto\src\ProcessSupervisor.php(382): Nesk\Rialto\ProcessSupervisor->readNextProcessValue(true)
#2 D:\wwwroot\pscraper\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(84): Nesk\Rialto\ProcessSupervisor->executeInstruction(Object(Nesk\Rialto\Instruction))
#3 D:\wwwroot\pscraper\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(100): Nesk\Rialto\AbstractEntryPoint->proxyAction('call', 'launch', Array)
#4 D:\wwwroot\pscraper\vendor\jaeger\querylist-puppeteer\Chrome.php(32): Nesk\Rialto\AbstractEntryPoint->__call('launch', Array)
#5 D:\wwwroot\pscraper\vendor\jaeger\querylist-puppeteer\Chrome.php(24): QL\Ext\Chrome::render(Object(QL\QueryList), 'https://ll...', Array)
#6 [internal function]: QL\QueryList->QL\Ext\{closure}('https://ll...')
#7 D:\wwwroot\pscraper\vendor\jaeger\querylist\src\QueryList.php(67): Closure->call(Object(QL\QueryList), 'https://ll...')
#8 D:\wwwroot\pscraper\libs\SScraper.php(29): QL\QueryList->__call('chrome', Array)
#9 D:\wwwroot\pscraper\test.php(6): Pscraper\SScraper->getGoodsParams('https://ll...')
#10 {main}`

**Comment by akrick** [comment]
调试异常返回这个信息：

`Socket operation failed: 远程主机强迫关闭了一个现有的连接`

**Comment by akrick** [comment]
`异常码：10054  异常消息：Socket operation failed: 远程主机强迫关闭了一个现有的连接。\r\n
 (SOCKET_ECONNRESET)`
